### ISSUE TITLE
spsc experiment.

### ISSUE THREAD

**Issue by ghost** [duoxehyon/sequencer-client-rs#6]
![image](https://user-images.githubusercontent.com/130279081/234833787-88ec1a9a-87d8-4653-9821-c258acab0112.png)

https://github.com/0xCuteSocks/sequencer-client-rs/tree/spsc

**Comment by ghost** [comment]
single thread + spsc
![image](https://user-images.githubusercontent.com/130279081/234867006-bdf32bcc-c575-47b0-bf01-1bbe27d5ff93.png)

**Comment by duoxehyon** [comment]
Thinking of maybe using select! to race data b/w threads using spsc

**Comment by ghost** [comment]
single thread two client mpsc, no race.
![image](https://user-images.githubusercontent.com/130279081/234912050-60559e18-8e28-407b-a3df-3e56317d555f.png)

**Comment by duoxehyon** [comment]
Looks good, will add when i get back
